# Generated by Django 5.2.7 on 2025-10-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id_mainarticle', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id_alternativearticle', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
