# Generated by Django 5.2.7 on 2025-11-12 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id_mainarticle', models.CharField(primary_key=True, serialize=False)),
                ('alternativearticle', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCompany',
            fields=[
                ('id_ArtCompany', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companies')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articles')),
            ],
            options={
                'unique_together': {('article', 'company')},
            },
        ),
    ]
