# Generated by Django 5.2.7 on 2025-10-14 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
        ('company', '0002_alter_companies_id_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='id_mainarticle',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ArticleCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articles')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companies')),
            ],
            options={
                'unique_together': {('article_id', 'company_id')},
            },
        ),
    ]
