# Generated by Django 5.2.7 on 2025-10-14 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_articles_id_mainarticle_articlecompany'),
        ('company', '0002_alter_companies_id_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecompany',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='articlecompany',
            old_name='company_id',
            new_name='company',
        ),
        migrations.AlterUniqueTogether(
            name='articlecompany',
            unique_together={('article', 'company')},
        ),
    ]
