# Generated by Django 5.2.7 on 2025-10-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_rename_article_id_articlecompany_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.CharField(default='sin categoria', max_length=50),
            preserve_default=False,
        ),
    ]
