# Generated by Django 5.2.7 on 2025-10-16 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_articles_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='money',
            new_name='price',
        ),
    ]
