# Generated by Django 5.2.7 on 2025-10-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_rename_money_articles_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecompany',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
