# Generated by Django 5.2.7 on 2025-10-16 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_articlecompany_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='category',
        ),
    ]
