# Generated by Django 5.2.7 on 2025-11-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_remove_articles_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='id_alternativearticle',
            new_name='alternativearticle',
        ),
        migrations.RemoveField(
            model_name='articlecompany',
            name='id',
        ),
        migrations.AddField(
            model_name='articlecompany',
            name='id_ArtCompany',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
