# Generated by Django 5.2.7 on 2025-11-12 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborators',
            fields=[
                ('id_Collaborator', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('home_address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollaboratorCompany',
            fields=[
                ('id_ColabCompany', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companies')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborator.collaborators')),
            ],
            options={
                'unique_together': {('collaborator', 'company')},
            },
        ),
    ]
