# Generated by Django 5.2.7 on 2025-12-02 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborators',
            old_name='home_address',
            new_name='address',
        ),
    ]
