# Generated by Django 5.2.7 on 2025-10-14 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0002_alter_collaborators_id_collaborator_and_more'),
        ('company', '0002_alter_companies_id_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaboratorcompany',
            old_name='collaborator_id',
            new_name='collaborator',
        ),
        migrations.RenameField(
            model_name='collaboratorcompany',
            old_name='company_id',
            new_name='company',
        ),
        migrations.AlterUniqueTogether(
            name='collaboratorcompany',
            unique_together={('collaborator', 'company')},
        ),
    ]
