# Generated by Django 5.2.7 on 2025-11-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0003_rename_collaborator_id_collaboratorcompany_collaborator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboratorcompany',
            name='id',
        ),
        migrations.AddField(
            model_name='collaboratorcompany',
            name='id_ColabCompany',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='id_Collaborator',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
