# Generated by Django 5.2.7 on 2025-11-12 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id_Request', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default='prerequest', max_length=20)),
                ('order_workshop', models.TextField(blank=True, null=True)),
                ('store', models.TextField(blank=True, null=True)),
                ('request_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestActions',
            fields=[
                ('id_RequestActions', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('authorized', 'Autorizado'), ('declined', 'Rechazado')], max_length=10)),
                ('comment', models.TextField()),
                ('requestactions_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnExchange',
            fields=[
                ('id_returnExchange', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('returnE_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id_supply', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('photo', models.CharField(max_length=255, null=True)),
                ('document', models.CharField(max_length=255, null=True)),
                ('supply_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id_acceptance', models.AutoField(primary_key=True, serialize=False)),
                ('acceptance_datetime', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articles')),
            ],
        ),
    ]
