# Generated by Django 5.2.7 on 2025-10-20 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0007_remove_articles_category'),
        ('collaborator', '0003_rename_collaborator_id_collaboratorcompany_collaborator_and_more'),
        ('company', '0002_alter_companies_id_company'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRequest',
            fields=[
                ('id_PreRequest', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default='prerequest', max_length=20)),
                ('order_workshop', models.TextField(null=True)),
                ('store', models.TextField(null=True)),
                ('requested_datetime', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articles')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id_Request', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=23)),
                ('type', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default='request', max_length=20)),
                ('order_workshop', models.TextField(null=True)),
                ('store', models.TextField(null=True)),
                ('request_datetime', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articles')),
                ('collaborator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborations', to='collaborator.collaborators')),
                ('prerequest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='application.prerequest')),
                ('requestingCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='company.companies')),
                ('supplierCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='company.companies')),
            ],
        ),
        migrations.CreateModel(
            name='Deliverie',
            fields=[
                ('id_Deliverie', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('photo', models.CharField(max_length=255, null=True)),
                ('document', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(default='delivered', max_length=20)),
                ('deliverie_datetime', models.DateTimeField(auto_now_add=True)),
                ('companydelivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_company', to='company.companies')),
                ('companyreceives', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_company', to='company.companies')),
                ('persondelivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_made', to='users.users')),
                ('personreceives', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_received', to='collaborator.collaborators')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliverie', to='application.request')),
            ],
        ),
        migrations.CreateModel(
            name='Decline',
            fields=[
                ('id_Decline', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=23)),
                ('comment', models.TextField()),
                ('status', models.CharField(default='declined', max_length=20)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('decline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decline', to='users.users')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decline', to='application.request')),
            ],
        ),
        migrations.CreateModel(
            name='Authorize',
            fields=[
                ('id_Authorize', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=23)),
                ('comment', models.TextField()),
                ('status', models.CharField(default='authorized', max_length=20)),
                ('authorized_datetime', models.DateTimeField(auto_now_add=True)),
                ('authorize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authorization', to='application.request')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnExchange',
            fields=[
                ('id_return_exchange', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('return_datetime', models.DateTimeField(auto_now_add=True)),
                ('deliverie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_exchange', to='application.deliverie')),
                ('deliverycompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_company_return', to='company.companies')),
                ('receivedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_by', to='users.users')),
                ('receivingcompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_company_return', to='company.companies')),
                ('returnenby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_by', to='collaborator.collaborators')),
            ],
        ),
    ]
