# Generated by Django 5.2.7 on 2025-10-21 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        ('company', '0002_alter_companies_id_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequest',
            name='requestingCompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prerequests_as_requester', to='company.companies'),
        ),
        migrations.AddField(
            model_name='prerequest',
            name='supplierCompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prerequests_as_supplier', to='company.companies'),
        ),
        migrations.AlterField(
            model_name='prerequest',
            name='article',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='prerequest',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='returnexchange',
            name='id_return_exchange',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
