# Generated by Django 5.2.7 on 2025-11-12 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        ('collaborator', '0001_initial'),
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborations', to='collaborator.collaborators'),
        ),
        migrations.AddField(
            model_name='request',
            name='requestingCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='company.companies'),
        ),
        migrations.AddField(
            model_name='request',
            name='supplierCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='company.companies'),
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acceptance',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.request'),
        ),
        migrations.AddField(
            model_name='requestactions',
            name='acceptance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.acceptance'),
        ),
        migrations.AddField(
            model_name='requestactions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnexchange',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collaborator.collaborators'),
        ),
        migrations.AddField(
            model_name='returnexchange',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supply',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborator.collaborators'),
        ),
        migrations.AddField(
            model_name='supply',
            name='requestActions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.requestactions'),
        ),
        migrations.AddField(
            model_name='supply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnexchange',
            name='supply',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.supply'),
        ),
    ]
