# Generated by Django 5.2.7 on 2025-10-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_prerequest_requestingcompany_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequest',
            name='order_workshop',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prerequest',
            name='store',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='order_workshop',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='store',
            field=models.TextField(blank=True, null=True),
        ),
    ]
