# Generated by Django 5.2.7 on 2025-11-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='photo',
        ),
        migrations.AddField(
            model_name='request',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supply',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='supplies/'),
        ),
    ]
