# Generated by Django 5.2.7 on 2025-10-21 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_prerequest_order_workshop_and_more'),
        ('collaborator', '0003_rename_collaborator_id_collaboratorcompany_collaborator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequest',
            name='Collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collaborator.collaborators'),
        ),
    ]
