# Generated by Django 5.2.7 on 2025-11-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_supply_photo_request_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='archived_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
