# Generated by Django 5.2.7 on 2025-10-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_prerequest_collaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequest',
            name='amount',
            field=models.IntegerField(blank=True),
        ),
    ]
