# Generated by Django 5.2.7 on 2025-12-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_request_archived_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Pagado'), ('unpaid', 'No Pagado')], default='unpaid', help_text='Estado de pago para solicitudes de Consumo Personal', max_length=10),
        ),
    ]
