# Generated by Django 5.2.7 on 2025-10-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_prerequest_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequest',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
