# Generated by Django 5.2.7 on 2025-12-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_supply_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
