# Generated by Django 5.2.7 on 2025-12-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_request_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='document_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='document_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
