# Generated by Django 5.2.7 on 2025-10-21 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_prerequest_amount'),
        ('collaborator', '0003_rename_collaborator_id_collaboratorcompany_collaborator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prerequest',
            name='Collaborator',
        ),
        migrations.AddField(
            model_name='prerequest',
            name='collaborator',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='collaborator.collaborators'),
            preserve_default=False,
        ),
    ]
