# Generated by Django 5.2.7 on 2025-10-22 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_prerequest_collaborator_and_more'),
        ('collaborator', '0003_rename_collaborator_id_collaboratorcompany_collaborator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequest',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collaborator.collaborators'),
        ),
    ]
