# Generated by Django 5.2.7 on 2025-10-27 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_prerequest_collaborator'),
        ('collaborator', '0003_rename_collaborator_id_collaboratorcompany_collaborator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnexchange',
            name='type',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborations', to='collaborator.collaborators'),
        ),
    ]
