# Generated by Django 5.2.7 on 2025-10-30 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_returnexchange_type_alter_request_collaborator'),
        ('collaborator', '0003_rename_collaborator_id_collaboratorcompany_collaborator_and_more'),
        ('users', '0002_remove_users_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequest',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequests_as_applicant', to='users.users'),
        ),
        migrations.AlterField(
            model_name='prerequest',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prerequests_as_collaborator', to='collaborator.collaborators'),
        ),
    ]
