# Generated by Django 5.2.7 on 2025-11-02 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_prerequest_applicant_and_more'),
        ('article', '0008_rename_id_alternativearticle_articles_alternativearticle_and_more'),
        ('collaborator', '0004_remove_collaboratorcompany_id_and_more'),
        ('users', '0002_remove_users_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decline',
            name='decline',
        ),
        migrations.RemoveField(
            model_name='decline',
            name='request',
        ),
        migrations.RemoveField(
            model_name='deliverie',
            name='companydelivery',
        ),
        migrations.RemoveField(
            model_name='deliverie',
            name='companyreceives',
        ),
        migrations.RemoveField(
            model_name='deliverie',
            name='persondelivery',
        ),
        migrations.RemoveField(
            model_name='deliverie',
            name='personreceives',
        ),
        migrations.RemoveField(
            model_name='deliverie',
            name='request',
        ),
        migrations.RemoveField(
            model_name='returnexchange',
            name='deliverie',
        ),
        migrations.RemoveField(
            model_name='prerequest',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='prerequest',
            name='collaborator',
        ),
        migrations.RemoveField(
            model_name='prerequest',
            name='requestingCompany',
        ),
        migrations.RemoveField(
            model_name='prerequest',
            name='supplierCompany',
        ),
        migrations.RemoveField(
            model_name='request',
            name='prerequest',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='applicant',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='returnexchange',
            old_name='id_return_exchange',
            new_name='id_returnExchange',
        ),
        migrations.RenameField(
            model_name='returnexchange',
            old_name='return_datetime',
            new_name='returnE_datetime',
        ),
        migrations.RemoveField(
            model_name='request',
            name='position',
        ),
        migrations.RemoveField(
            model_name='returnexchange',
            name='deliverycompany',
        ),
        migrations.RemoveField(
            model_name='returnexchange',
            name='receivedby',
        ),
        migrations.RemoveField(
            model_name='returnexchange',
            name='receivingcompany',
        ),
        migrations.RemoveField(
            model_name='returnexchange',
            name='returnenby',
        ),
        migrations.RemoveField(
            model_name='returnexchange',
            name='type',
        ),
        migrations.AddField(
            model_name='returnexchange',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collaborator.collaborators'),
        ),
        migrations.AddField(
            model_name='returnexchange',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.users'),
        ),
        migrations.AlterField(
            model_name='request',
            name='article',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default='prerequest', max_length=20),
        ),
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id_acceptance', models.AutoField(primary_key=True, serialize=False)),
                ('acceptance_datetime', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articles')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='RequestActions',
            fields=[
                ('id_RequestActions', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('authorize', 'Autorizado'), ('decline', 'Rechazado')], max_length=10)),
                ('comment', models.TextField()),
                ('requestactions_datetime', models.DateTimeField(auto_now_add=True)),
                ('acceptance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.acceptance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id_supply', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('photo', models.CharField(max_length=255, null=True)),
                ('document', models.CharField(max_length=255, null=True)),
                ('supply_datetime', models.DateTimeField(auto_now_add=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborator.collaborators')),
                ('requestActions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.requestactions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
        migrations.AddField(
            model_name='returnexchange',
            name='supply',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.supply'),
        ),
        migrations.DeleteModel(
            name='Authorize',
        ),
        migrations.DeleteModel(
            name='Decline',
        ),
        migrations.DeleteModel(
            name='Deliverie',
        ),
        migrations.DeleteModel(
            name='PreRequest',
        ),
    ]
