# Generated by Django 5.2.7 on 2025-10-16 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0006_alter_articlecompany_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_Category', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articles')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'unique_together': {('category', 'article')},
            },
        ),
    ]
