# Generated by Django 5.2.7 on 2025-10-17 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_active_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='active',
        ),
    ]
