# Generated by Django 5.2.7 on 2025-11-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_category_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryarticle',
            name='id',
        ),
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoryarticle',
            name='id_CatArticle',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
